kind: "app"
schema_version: "v1"
spec:
  # заполнить по маске "{{имя-курса}}-ui"
  name: "[TODO]"
  name.production: "main"
  desc: 'UI для приложения "[TODO]" | [TODO]'
  desc.production: '[PROD] Приложение "[TODO]" | [TODO]'
  store_logs: true
  service_mesh: true
  nat: false
  nat.production: true
  env:
    - key: "APP_NAME"
      value: "${{ values.env.APP_NAME }}"
    - key: "FEEDBACK_API_URL"
      value: "${{ values.env.FEEDBACK_API_URL }}"
    - key: "CLICKSTREAM_HOST"
      value: "${{ values.CLICKSTREAM_HOST }}"
    - key: CDN_HOST
      value: "${{ values.SPA_BASE_CDN_HOST }}"
    - key: S3_HOST
      value: "${{ values.SPA_BASE_S3_HOST }}"
    - key: S3_ID
      value: "${{ values.SPA_BASE_S3_ID }}"
    - key: S3_KEY
      value: "${{ values.SPA_BASE_S3_KEY }}"
    - key: S3_BUCKET
      value: "${{ values.SPA_BASE_S3_BUCKET }}"
  services:
    - name: "main"
      mem: "${{ values.services.main.mem_mb }}"
      constraint: "role=node"
      amount: "${{ values.services.main.amount }}"
      max_parallel: "${{ values.services.main.max_parallel }}"
      endpoints:
        - name: "main"
          port: 80
          type: "http"
          max_conns: 1000
